baseURL = "https://www.james-o.tools/"
languageCode = "en-gb"
title = "James O'Toole"
theme = "blind"
paginate = 5

[params]
  email = "otoolej012@gmail.com"
  github = "https://www.github.com/SmileyJames/"
  linkdin = "https://linkdin.com/JamesOToole/"
